apiVersion: v1
kind: Service
metadata:
  name: external-gateway-service
spec:
  type: LoadBalancer
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000