apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ${IMAGE}
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: 2
              memory: "1024Mi"
            limits:
              cpu: 2
              memory: "1024Mi"
          env:
            - name: SERVICE_URL
              value: "http://internal-gateway-service"